version: '3.6'

services:
  database:
    image: 'postgres'
    container_name: 'pg'
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: 'my_todo'
      POSTGRES_USER: 'test'
      POSTGRES_PASSWORD: 'test'
